quicktest:
  stage: test
  only:
    - master
  variables:
    GIT_STRATEGY: fetch
  script:
    - gradlew -Pdist=publishdists clean build test -x javadoc --info --stacktrace --no-daemon
  tags:
    - win
  cache:
    paths:
      - binaries/
      
testreport:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - gradlew testReport
  tags:
    - win
  artifacts:
    paths:
      - testreport
  only:
    - master
  when: always
