image: julakali/openjdk8-xvfb:latest

stages:
  - preBuild
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - Xvfb -ac :99 -screen 0 1280x1024x16 &
  - export DISPLAY=:99

variables:
  GRADLE_ARGS: "--info --stacktrace"

cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: false
  paths:
    - .gradle/wrapper
    - .gradle/caches

preBuild:
  stage: preBuild
  script:
    - ls -la /tmp/
    - whoami
    - mkdir -p /tmp/
    - df -h /tmp/
    - dd if=/dev/urandom of=/tmp/randomPreBuild bs=1M count=10
    - ./gradlew -Pdist=addongradleplugin clean build test install -x javadoc $GRADLE_ARGS

build:
  stage: build
  script:
    - ls -la /tmp/
    - whoami
    - mkdir -p /tmp/
    - df -h /tmp/
    - dd if=/dev/urandom of=/tmp/randomBuild bs=1M count=10
    - ./gradlew -Pdist=publishdists clean build -x test -x javadoc $GRADLE_ARGS

test:
  stage: test
  script:
    - ls -la /tmp/
    - whoami
    - mkdir -p /tmp/
    - df -h /tmp/
    - dd if=/dev/urandom of=/tmp/randomTest bs=1M count=10
    - ./gradlew -Pdist=publishdists test -x javadoc
  artifacts:
    paths:
    - "*/build/reports/tests/test"
    expire_in: 4 week
    when: always
    
#deploy:
#  stage: deploy
#  script:
#    - ./gradlew publish
#  only:
#    - master
#    - development

after_script:
- echo "End CI"