quicktest:
  only:
    - master
  stage: test
  variables:
    GIT_STRATEGY: fetch
  script:
    - gradlew --no-daemon --parallel clean :jadex-applications-micro:test :jadex-integration-test:test test testReport -x :jadex-integration-performance-test:test -x javadoc -x lint -x generatereleaseJavadoc -x generatedebugJavadoc -x lintVitalRelease -x transformClassesWithDexForRelease -x testDebugUnitTest -x processSchemas
  tags:
    - win
  artifacts:
    paths:
    - "*/build/reports/tests/test"
    expire_in: 4 week
    when: always
    
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  tags:
    - win
  artifacts:
    paths:
    - public
  only:
  - master
  when: always
