quicktest:
  only:
    - master
  stage: test
  variables:
    GIT_STRATEGY: fetch
  script:
    - gradlew --no-daemon --parallel clean :jadex-applications-micro:test :jadex-integration-test:test test -x :jadex-integration-performance-test:test -x javadoc -x lint -x generatereleaseJavadoc -x generatedebugJavadoc -x lintVitalRelease -x transformClassesWithDexForRelease -x testDebugUnitTest -x processSchemas
  tags:
    - win
  cache:
    paths:
    - binaries/

    
pages:
  stage: deploy
  GIT_STRATEGY: none
  script:
    - gradlew --no-daemon testReport
  tags:
    - win
  artifacts:
    paths:
    - public
  only:
  - master
  when: always
