quicktest:
  only:
    - master
  stage: test
  variables:
    GIT_STRATEGY: fetch
  script:
    - gradlew --parallel --continue :jadex-applications-micro:test :jadex-integration-test:test test -x :jadex-integration-performance-test:test -x javadoc -x lint -x generatereleaseJavadoc -x lintVitalRelease -x transformClassesWithDexForRelease -x processSchemas
  tags:
    - win
  cache:
    paths:
    - binaries/

    
testreport:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - ipconfig
    - gradlew testReport
  tags:
    - win
  artifacts:
    paths:
    - testreport
  only:
  - master
  when: always
