site_name: Jadex Active Components ${jadexversiontitle} Documentation

theme:
  name: readthedocs
  custom_dir: theme
  
docs_dir: docs

extra_css: ['jadexstyles.css']


pages:
- 'index.md'

- Getting Started: 'getting-started/getting-started.md'
- Platform: 'platform/platform.md'
- Components: 'components/components.md'
- Services: 'services/services.md'
- Futures: 'futures/futures.md'
- Remote Communication: 'remote/remote.md'
- Component Types: 'component-types/component-types.md'
- Android: 'android/android.md'
- Web API: 'webapi/webapi.md'
#- Simulation: 'simulation/simulation.md'
- Quickstart Tutorial:
    - 'tutorials/quickstart/01 Introduction.md'
    - 'tutorials/quickstart/02 Time Service Interface.md'
    - 'tutorials/quickstart/03 Time User.md'
    - 'tutorials/quickstart/04 Time Provider.md'
    - 'tutorials/quickstart/05 Summary.md'
- Active Components Tutorial:
    - 'tutorials/ac/01 Introduction.md'
    - 'tutorials/ac/03 Active Components.md'
    - 'tutorials/ac/04 Required Services.md'
    - 'tutorials/ac/05 Provided Services.md'
    - 'tutorials/ac/06 Composition.md'
    - 'tutorials/ac/07 External Access.md'
    - 'tutorials/ac/08 Security.md'
    - 'tutorials/ac/09 Application Integration.md'
- BDIV3 Tutorial:
    - 'tutorials/bdiv3/01 Introduction.md'
    - 'tutorials/bdiv3/02 Your first BDI Agent.md'
    - 'tutorials/bdiv3/03 Using Plans.md'
    - 'tutorials/bdiv3/04 Using Beliefs.md'
    - 'tutorials/bdiv3/05 Using Goals.md'
    - 'tutorials/bdiv3/06 Using Capabilities.md'
    - 'tutorials/bdiv3/07 Using Services.md'
    - 'tutorials/bdiv3/08 External Processes.md'
    - 'tutorials/bdiv3/09 Conclusion.md'
- BPMN Tutorial:
    - 'tutorials/bpmn/01 Introduction.md'
    - 'tutorials/bpmn/02 Installation.md'
    - 'tutorials/bpmn/03 Basic Processes.md'
    - 'tutorials/bpmn/04 Data and Parameters.md'
    - 'tutorials/bpmn/05 Events and Messages.md'
    - 'tutorials/bpmn/06 Custom Functionality.md'
- Jadex Active Components User Guide:
    - 'guides/ac/01 Introduction.md'
    - 'guides/ac/02 Active Components.md'
    - 'guides/ac/03 Asynchronous Programming.md'
    - 'guides/ac/04 Component Specification.md'
    - 'guides/ac/05 Services.md'
    - 'guides/ac/06 Web Service Integration.md'
    - 'guides/ac/07 Platform Awareness.md'
    - 'guides/ac/08 Security.md'
- BDIV3 User Guide:
    - 'guides/bdiv3/01 Introduction.md'
    - 'guides/bdiv3/02 Concepts.md'
    - 'guides/bdiv3/03 Agent Specification.md'
    - 'guides/bdiv3/04 Imports.md'
    - 'guides/bdiv3/05 Capabilities.md'
    - 'guides/bdiv3/06 Beliefs.md'
    - 'guides/bdiv3/07 Goals.md'
    - 'guides/bdiv3/08 Plans.md'
    - 'guides/bdiv3/09 Events.md'
    - 'guides/bdiv3/10 Expressions.md'
    - 'guides/bdiv3/11 Conditions.md'
    - 'guides/bdiv3/12 Properties.md'
    - 'guides/bdiv3/13 Configurations.md'
    - 'guides/bdiv3/14 External Interactions.md'
    - 'guides/bdiv3/16 Predefined Capabilities.md'
- Environment Guide:
    - 'guides/env/01 Introduction.md'
    - 'guides/env/02 Concepts.md'
    - 'guides/env/03 Domain Model.md'
    - 'guides/env/04 Component Interaction.md'
    - 'guides/env/05 2D Visualization.md'
    - 'guides/env/06 3D Visualization.md'
    - 'guides/env/07 Environment Instance.md'
    - 'guides/env/08 Standalone.md'
- Jadex Active Components Tools:
    - 'tools/01 Introduction.md'
    - 'tools/02 JCC Overview.md'
    - 'tools/03 Starter.md'
    - 'tools/04 Awareness Settings.md'
    - 'tools/05 Security Settings.md'
    - 'tools/06 Library Center.md'
    - 'tools/07 Deployer.md'
    - 'tools/08 Chat.md'
    - 'tools/09 Simulation Control.md'
    - 'tools/10 Component Viewer.md'
    - 'tools/11 Test Center.md'
    - 'tools/12 Debugger.md'
    - 'tools/13 Cli Email Signer.md'
    - 'tools/14 Relay Server.md'
    - 'tools/15 ADF Checker.md'
    - 'tools/A1 Conversation Center.md'
    - 'tools/A2 Communication Analyzer.md'
    - 'tools/A3 Directory Facilitator.md'
- FAQ: 'faq/faq.md'
