site_name: Jadex ${jadexversion} Documentation
theme: readthedocs
pages:

- 'index.md'

- Quickstart Tutorial:
    - 'Quickstart Tutorial/01 Introduction.md'
    - 'Quickstart Tutorial/02 Time Service Interface.md'
    - 'Quickstart Tutorial/03 Time User.md'
    - 'Quickstart Tutorial/04 Time Provider.md'
    - 'Quickstart Tutorial/05 Summary.md'
- AC Tutorial:
    - 'AC Tutorial/01 Introduction.md'
    - 'AC Tutorial/02 Installation.md'
    - 'AC Tutorial/03 Active Components.md'
    - 'AC Tutorial/04 Required Services.md'
    - 'AC Tutorial/05 Provided Services.md'
    - 'AC Tutorial/06 Composition.md'
    - 'AC Tutorial/07 External Access.md'
    - 'AC Tutorial/08 Security.md'
    - 'AC Tutorial/09 Application Integration.md'
- BDI V3 Tutorial:
    - 'BDI V3 Tutorial/01 Introduction.md'
    - 'BDI V3 Tutorial/02 Starting an Agent.md'
    - 'BDI V3 Tutorial/03 Using Plans.md'
    - 'BDI V3 Tutorial/04 Using Beliefs.md'
    - 'BDI V3 Tutorial/05 Using Goals.md'
    - 'BDI V3 Tutorial/06 Using Capabilities.md'
    - 'BDI V3 Tutorial/07 Using Services.md'
    - 'BDI V3 Tutorial/08 External Processes.md'
    - 'BDI V3 Tutorial/09 Conclusion.md'
- BPMN Tutorial:
    - 'BPMN Tutorial/01 Introduction.md'
    - 'BPMN Tutorial/02 Installation.md'
    - 'BPMN Tutorial/03 Basic Processes.md'
    - 'BPMN Tutorial/04 Data and Parameters.md'
    - 'BPMN Tutorial/05 Events and Messages.md'
    - 'BPMN Tutorial/06 Custom Functionality.md'
- BDI Tutorial:
    - 'BDI Tutorial/01 Introduction.md'
    - 'BDI Tutorial/02 Starting an Agent.md'
    - 'BDI Tutorial/03 Using Plans.md'
    - 'BDI Tutorial/04 Using Beliefs.md'
    - 'BDI Tutorial/05 Using Capabilities.md'
    - 'BDI Tutorial/06 Using Goals.md'
    - 'BDI Tutorial/07 Using Events.md'
    - 'BDI Tutorial/08 External Processes.md'
    - 'BDI Tutorial/09 Conclusion.md'
    - 'BDI Tutorial/Bibliography.md'

- AC User Guide:
    - 'AC User Guide/01 Introduction.md'
    - 'AC User Guide/02 Active Components.md'
    - 'AC User Guide/03 Asynchronous Programming.md'
    - 'AC User Guide/04 Component Specification.md'
    - 'AC User Guide/05 Services.md'
    - 'AC User Guide/06 Web Service Integration.md'
    - 'AC User Guide/07 Platform Awareness.md'
    - 'AC User Guide/08 Security.md'
- BDI User Guide:
    - 'BDI User Guide/01 Introduction.md'
    - 'BDI User Guide/02 Concepts.md'
    - 'BDI User Guide/03 Agent Specification.md'
    - 'BDI User Guide/04 Imports.md'
    - 'BDI User Guide/05 Capabilities.md'
    - 'BDI User Guide/06 Beliefs.md'
    - 'BDI User Guide/07 Goals.md'
    - 'BDI User Guide/08 Plans.md'
    - 'BDI User Guide/09 Events.md'
    - 'BDI User Guide/10 Expressions.md'
    - 'BDI User Guide/11 Conditions (old).md'
    - 'BDI User Guide/12 Properties.md'
    - 'BDI User Guide/13 Configurations.md'
    - 'BDI User Guide/14 External Interactions.md'
    - 'BDI User Guide/16 Predefined Capabilities.md'
    - 'BDI User Guide/D FAQ & HOWTO (old).md'
    - 'BDI User Guide/F Bibliography (old).md'
- Env User Guide:
    - 'Env User Guide/01 Introduction.md'
    - 'Env User Guide/02 Concepts.md'
    - 'Env User Guide/03 Domain Model.md'
    - 'Env User Guide/04 Component Interaction.md'
    - 'Env User Guide/05 2D Visualization.md'
    - 'Env User Guide/06 3D Visualization.md'
    - 'Env User Guide/07 Environment Instance.md'
    - 'Env User Guide/08 Standalone.md'
- Android User Guide:
    - 'Android User Guide/01 Introduction.md'
    - 'Android User Guide/02 Installation.md'
    - 'Android User Guide/03 Using Jadex on Android.md'
    - 'Android User Guide/04 Using BDIv3.md'
    - 'Android User Guide/05 PlatformApp - ClientApp Separation.md'
- AC Tool Guide:
    - 'AC Tool Guide/01 Introduction.md'
    - 'AC Tool Guide/02 JCC Overview.md'
    - 'AC Tool Guide/03 Starter.md'
    - 'AC Tool Guide/04 Awareness Settings.md'
    - 'AC Tool Guide/05 Security Settings .md'
    - 'AC Tool Guide/06 Library Center.md'
    - 'AC Tool Guide/07 Deployer.md'
    - 'AC Tool Guide/08 Chat.md'
    - 'AC Tool Guide/09 Simulation Control.md'
    - 'AC Tool Guide/10 Component Viewer.md'
    - 'AC Tool Guide/11 Test Center.md'
    - 'AC Tool Guide/12 Debugger.md'
    - 'AC Tool Guide/13 Cli Email Signer.md'
    - 'AC Tool Guide/14 Relay Server.md'
    - 'AC Tool Guide/15 ADF Checker.md'
    - 'AC Tool Guide/A1 Conversation Center.md'
    - 'AC Tool Guide/A2 Communication Analyzer.md'
    - 'AC Tool Guide/A3 Directory Facilitator.md'
